// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abykkbivfeywymwgunmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieWtrYml2ZmV5d3ltd2d1bm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTU3MzUsImV4cCI6MjA2MjEzMTczNX0.2EzaefnhsQPoXSHDhHprCMbc7Ec9C1p2Rqwn25LBmFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);